### ISSUE TITLE
Excellent job with your page design!

### ISSUE THREAD

**Issue by josephtkim** [kumajelly/prj-rev-bwfs-dasmoto#1]
Great job with your page design. The layout of the page and styling are properly applied as well. Keep up the great work!

**Comment by kumajelly** [comment]
Hi @josephtkim thanks again!
I updated both files (index.html, index.css) with the changes you suggested. And added the nav bar which works ok, not great.

prj-rev-bwfs-dasmoto/Dasmoto/index.html
prj-rev-bwfs-dasmoto/Dasmoto/resources/css/index.css

Also, learning how to use Github, wasn't sure how to link back to the files on Github.
