### ISSUE TITLE
Important: Some formatting changes for your HTML code.

### ISSUE THREAD

**Issue by josephtkim** [kumajelly/prj-rev-bwfs-dasmoto#2]
In HTML, code that is nested, or inside of another element, should only be indented relative to the outer, containing element. In addition, it is a good idea to place each section of the page inside of separate div elements, to improve the code and page structure. Here is how you might apply this to your code:

```html
<body>
    <h1>Dasmoto's Arts and Crafts Supply</h1>

    <div>
      <h2 class="brushes">Brushes</h2>
      <img src="resources/hacksaw.jpeg" alt="hacksaw brushes">
      <h3>Hacksaw Brushes</h3>
      <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="cost">Starting at $3.00 / brush.</span></p>
    </div>

    <div>
      <h2 class="frames">Frames</h2>
      <img src="resources/frames.jpeg" alt="art frames">
      <h3>Art Frames (assorted)</h3>
      <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="cost">Starting at $2.00 / frame.</span></p>
    </div>

    <div>
      <h2 class="paint">Paint</h2>
      <img src="resources/finnish.jpeg" alt="finnish paint">
      <h3>Clean Finnish Paint</h3>
      <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="cost">Starting at $5.00 / tube.</span></p>
    </div>
</body>
```

**Comment by kumajelly** [comment]
Hi @josephtkim I cleaned up the formatting a bit, how does this look (also added a nav bar to try it out):
<body>
  <h1>Dasmoto's Arts and Crafts Supply</h1>

  <nav id="menu">
  <ul id="header-list">
    <li><a href="#brushes">Brushes</a></li>
    <li><a href="#frames">Frames</a></li>
    <li><a href="#paint">Paint</a></li>
  </ul>
  </nav>
  
  <div>
    <h2 id="brushes">Brushes</h2>
    <img src="resources/hacksaw.jpeg" alt="hacksaw brushes">
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="cost">Starting at $3.00 / brush.</span></p>
    <p><a href="#menu">Menu</a></p>
  </div>
   
  <div>
    <h2 id="frames">Frames</h2>
    <img src="resources/frames.jpeg" alt="art frames">
    <h3>Art Frames (assorted)</h3>
    <p>Assorted frames made of different material, including MDF, birchwood, and PDE. Select frames can be sanded and painted according to your needs. <span class="cost">Starting at $2.00 / frame.</span></p>
    <p><a href="#menu">Menu</a></p>
  </div>

  <div>
    <h2 id="paint">Paint</h2>
    <img src="resources/finnish.jpeg" alt="finnish paint">
    <h3>Clean Finnish Paint</h3>
    <p>Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="cost">Starting at $5.00 / tube.</span></p>
    <p><a href="#menu">Menu</a></p>
  </div>
  </body>

**Comment by kumajelly** [comment]
Hi @josephtkim how does this look now from a section? I added a nav bar to play with and a link at the end of each section to return to the nav bar from some other research:

```
  <nav id="menu">
  <ul id="header-list">
    <li><a href="#brushes">Brushes</a></li>
    <li><a href="#frames">Frames</a></li>
    <li><a href="#paint">Paint</a></li>
  </ul>
  </nav>
  
  <div>
    <h2 id="brushes">Brushes</h2>
    <img src="resources/hacksaw.jpeg" alt="hacksaw brushes">
    <h3>Hacksaw Brushes</h3>
    <p>Made of the highest quality oak, Hacksaw brushes are known for their weight and ability to hold paint in large amounts. Available in different sizes. <span class="cost">Starting at $3.00 / brush.</span></p>
    <p><a href="#menu">Menu</a></p>
  </div>
```

**Comment by josephtkim** [comment]
Hi @kumajelly I think that looks great! The links look correctly implemented, and I believe that should work just fine. It is important to test it out and see if it works how you expected, and make changes as needed.

**Comment by kumajelly** [comment]
Ok! Thanks again @josephtkim !
