### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by josephtkim** [kumajelly/prj-rev-bwfs-dasmoto#6]
**Grade: Meets Expectations**

**Summary:** I think you did a great job with your project implementation. The design of the page is well done, with proper layout and styling which follows the project spec closely. In addition, your code was well structured and easily readable.

There are a few areas of improvement here. First, there are some formatting changes that should be made to the HTML code for nested elements. You only want to indent when elements are nested in another element. Also, each section should be placed inside of div elements to separate them and improve the code structure. Another area was to give elements that are unique with individual styling an id name while giving elements that share styling a class name. 

As a further challenge, consider adding responsive design to your page. This might take some extra research, but can be a great way to learn and apply important web design concepts. Based on your work so far, I think you are up for the challenge. Keep up the good work!

**Comment by kumajelly** [comment]
Hi @josephtkim ! Thank you for the review.
Will go through and make the changes & corrections you suggested.
Do you have any resources to begin adding responsive design?

**Comment by josephtkim** [comment]
@kumajelly Here are a few resources you might check out to implement responsive design. 

The Bootstrap framework - http://getbootstrap.com/

Codecademy course on responsive design - https://www.codecademy.com/learn/learn-responsive-design

**Comment by kumajelly** [comment]
Thanks @josephtkim !
